config/routes.rb
Rails.application.routes.draw do

  # get 'password_resets/new'
  # get 'password_resets/edit'
  root 'home#index'
  resources :users
  resources :account_activations, only: [:edit]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout' => 'sessions#logout'
  get '/loggedout', to: 'sessions#loggedout'
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update] 

  def new
  end

  def edit
    
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    
    if @user
      @user.create_reset_digest      
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_path
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "cant be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset"
      redirect_to user_path
    else
      render 'edit'
    end
  end

 private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end

  # Confirms a valid user.
  def valid_user
    unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
      redirect_to root_path
    end
  end

  # check expiration date
  def check__expiration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset gas expired"
      redirect_to new_password_reset_path
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<div class="container-fluid">        
    <div class="row">
        
            <div class="jumbotron jumbotron-fluid ">
                <div class="container">
                    <div class="logo-section text-center">
                        <i class="lab la-twitter twit"></i>
                        <span class="display-5">Reset Password</span>
                        
                    </div>
                    <%= form_for(:user, url: new_password_reset_path(params[:id])) do |form| %>
                        <% if flash[:errors] %>    
                        <p class="alert alert-danger" role="alert">  <%= render 'shared/error_messages' %></p>   
                        <%end%>                     

                        <%= hidden_field_tag :email, @user.email %>

                        <div class="form-group">
                        <%= form.label :password %>
                        <%= form.password_field :password, :class => 'form-control', :placeholder => "Password" %>
                        
                        </div>
                        <div class="form-group">
                        <%= form.label :password_confirmation %>
                        <%= form.password_field :password_confirmation, :class => 'form-control', :placeholder => "Password" %>
                       
                        </div>
                       
                        <br>
                        <div class="actions">
                        <%= form.submit 'Update  password', class: 'btn btn-primary submit' %>
                        </div>
                        <br>
                        <% end %>
                        
                </div>
              

        </div>
       
    </div>
</div>

app/views/password_resets/new.html.erb
<div class="container-fluid">        
    <div class="row">
        
            <div class="jumbotron jumbotron-fluid ">
                <div class="container">
                    <div class="logo-section text-center">
                        <i class="lab la-twitter twit"></i>
                        <span class="display-5">Forgot password</span>
                        
                    </div>
                    <%= form_for(:password_reset, url: password_resets_path) do |form| %>                        

                        <div class="form-group">
                        <%= form.label :email, :class => 'auth-label' %>
                        <%= form.text_field :email,  :class => 'form-control', :placeholder => "Email" %>
                        </div>                        
                        <br>
                        <div class="actions">
                        <%= form.submit 'Submit', class: 'btn btn-primary submit' %>
                        </div>
                        <br>
                    <% end %>                       
                </div>
              

        </div>
       
    </div>
</div>